name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  publish-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install System Dependencies
        run: sudo apt-get update && sudo apt-get install -y rpm libarchive-tools

      - name: Install NPM Dependencies
        run: npm install

      - name: Build and Publish Binaries (GitHub Releases)
        run: npm run build:all -- -p always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
